global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["127.0.0.1:9090"]

  - job_name: node
    static_configs:
      - targets: ["127.0.0.1:9100"]

  - job_name: vllm
    metrics_path: /metrics
    static_configs:
      - targets: ["127.0.0.1:8000"]

  - job_name: llamacpp
    metrics_path: /metrics
    static_configs:
      - targets: ["127.0.0.1:8080"]
